apiVersion: batch/v1
kind: Job
metadata:
  name: msr4
spec:
  template:
    spec:
      containers:
      - name: aslr
        image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
        command: ["/bin/sh", "-c"]
        args: ["sleep 6h"]
        resources:
          limits:
            nvidia.com/gpu: 0
            memory: 4Gi
            cpu: 500m
          requests:
            nvidia.com/gpu: 0
            memory: 4Gi
            cpu: 500m
        volumeMounts:
        - mountPath: /extvol
          name: examplevol1
      volumes:
        - name: examplevol1
          persistentVolumeClaim:
            claimName: msvol4
      restartPolicy: Never
  backoffLimit: 4
